version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: P@55word
      MYSQL_ROOT_PASSWORD: P@55word
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: .
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: P@55word
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html  # Allows plugins/themes/etc.

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - certbot-webroot:/var/www/certbot

volumes:
  db_data:
  certbot-webroot:
